services:
  django-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: abeduc/oc-lettings:latest
    container_name: django-docker
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - empty-volume:/app/data/

volumes:
  empty-volume:
    external: true
