services:
  django-web-demo:
    build:
      context: .
      dockerfile: Dockerfile.demo
    image: abeduc/oc-lettings-demo
    container_name: django-docker-demo
    ports:
      - "8000:8000"
    env_file:
      - .env
