services:
  django-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: abeduc/oc-lettings
    container_name: django-docker
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - oc-lettings-data:/app/data/

volumes:
  oc-lettings-data:
    external: true
