# Run for PR on master to block merge if any workflows fails.
name: CI Operator

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
