# https://api-docs.render.com/reference/update-env-var
# https://stackoverflow.com/questions/8084389/bash-variable-in-single-quote

name: Deploy container

on:
  workflow_call:
    secrets:
      RENDER_TOKEN:
        required: true
      DJANGO_SECRET_KEY:
        required: true
      DJANGO_SENTRY_DSN:
        required: true
  workflow_dispatch:

jobs:
  deploy-container:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Update secret key
        run: |
          curl --request PUT \
               --url https://api.render.com/v1/services/${{ vars.RENDER_SERVICE }}/env-vars/DJANGO_SECRET_KEY \
               --header 'accept: application/json' \
               --header 'authorization: Bearer ${{ secrets.RENDER_TOKEN }}' \
               --header 'content-type: application/json' \
               --data '{"value": "'"${{ secrets.DJANGO_SECRET_KEY}}"'"}'
      - name: Update sentry url
        run: |
          curl --request PUT \
               --url https://api.render.com/v1/services/${{ vars.RENDER_SERVICE }}/env-vars/DJANGO_SENTRY_DSN \
               --header 'accept: application/json' \
               --header 'authorization: Bearer ${{ secrets.RENDER_TOKEN }}' \
               --header 'content-type: application/json' \
               --data '{"value": "'"${{ secrets.DJANGO_SENTRY_DSN}}"'"}'
      - name: Trigger deploy
        run: |
          curl ${{ vars.RENDER_DEPLOY_HOOK }}
