# https://api-docs.render.com/reference/update-env-var
# https://stackoverflow.com/questions/8084389/bash-variable-in-single-quote

name: Deploy container

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-container:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy
        run: |
          curl ${{ vars.RENDER_DEPLOY_HOOK }}
