# Run for Push on master to ensure test pass before deployment

name: Release Operator

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

  build-demo:
    needs: [ lint, test ]
    uses: ./.github/workflows/build-demo.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-clean:
    needs: [ lint, test ]
    uses: ./.github/workflows/build-clean.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    needs: [ build-demo ]
    uses: ./.github/workflows/deploy.yml
